In [1]:
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'
df = pd.read_csv(url)
df

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1
...,...,...,...,...,...,...,...,...,...
1457,referral,manufacturing,1,NaN,self_employed,north_america,4,0.53,1
1458,referral,technology,3,65259.0,student,europe,2,0.24,1
1459,paid_ads,technology,1,45688.0,student,north_america,3,0.02,1
1460,referral,NaN,5,71016.0,self_employed,north_america,0,0.25,1
1461,organic_search,finance,3,92855.0,student,north_america,3,0.41,1

In [2]:
df.isna().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               1334 non-null   object
 1   industry                  1328 non-null   object
 2   number_of_courses_viewed  1462 non-null   int64
 3   annual_income             1281 non-null   float64
 4   employment_status         1362 non-null   object
 5   location                  1399 non-null   object
 6   interaction_count         1462 non-null   int64
 7   lead_score                1462 non-null   float64
 8   converted                 1462 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 102.9+ KB

In [4]:
df.columns

Index(['lead_source', 'industry', 'number_of_courses_viewed', 'annual_income',
       'employment_status', 'location', 'interaction_count', 'lead_score',
       'converted'],
      dtype='object')

In [5]:
df.describe()

,number_of_courses_viewed,annual_income,interaction_count,lead_score,converted
count,1462.000000,1281.000000,1462.000000,1462.000000,1462.000000
mean,2.031464,59886.273224,2.976744,0.506108,0.619015
std,1.449717,15070.140389,1.681564,0.288465,0.485795
min,0.000000,13929.000000,0.000000,0.000000,0.000000
25%,1.000000,49698.000000,2.000000,0.262500,0.000000
50%,2.000000,60148.000000,3.000000,0.510000,1.000000
75%,3.000000,69639.000000,4.000000,0.750000,1.000000
max,9.000000,109899.000000,11.000000,1.000000,1.000000

In [6]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
categorical_columns

['lead_source', 'industry', 'employment_status', 'location']

In [12]:
numeric_columns = list([col for col in df.columns if col not in categorical_columns])
numeric_columns

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [20]:
def fill_column(series):
    if series.name in categorical_columns:
        return series.fillna('NA')
    else:
        return series.fillna(0.0)

df = df.apply(fill_column)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               1462 non-null   object
 1   industry                  1462 non-null   object
 2   number_of_courses_viewed  1462 non-null   int64
 3   annual_income             1462 non-null   float64
 4   employment_status         1462 non-null   object
 5   location                  1462 non-null   object
 6   interaction_count         1462 non-null   int64
 7   lead_score                1462 non-null   float64
 8   converted                 1462 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 102.9+ KB

### Question 1

What is the most frequent observation (mode) for the column `industry`?

- `NA`
- `technology`
- `healthcare`
- `retail`

In [24]:
df[['industry']].value_counts()

industry
retail           203
finance          200
other            198
education        187
healthcare       187
technology       179
manufacturing    174
NA               134
Name: count, dtype: int64

### Question 2

Create the [correlation matrix](https://www.google.com/search?q=correlation+matrix) for the numerical features of your dataset.
In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- `interaction_count` and `lead_score`
- `number_of_courses_viewed` and `lead_score`
- `number_of_courses_viewed` and `interaction_count`
- `annual_income` and `interaction_count`

In [26]:
numeric_columns

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score',
 'converted']

In [34]:
numeric_features = numeric_columns[:-1]
numeric_features

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [35]:
corr_matrix = df[numeric_features].corr()
corr_matrix

,number_of_courses_viewed,annual_income,interaction_count,lead_score
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879
annual_income,0.009770,1.000000,0.027036,0.015610
interaction_count,-0.023565,0.027036,1.000000,0.009888
lead_score,-0.004879,0.015610,0.009888,1.000000

In [36]:
corr_matrix_unstacked = corr_matrix.unstack().sort_values(ascending=False)
corr_matrix_unstacked
corr_matrix_unstacked[corr_matrix_unstacked < 1].sort_values(ascending=False).head()

annual_income      interaction_count    0.027036
interaction_count  annual_income        0.027036
annual_income      lead_score           0.015610
lead_score         annual_income        0.015610
interaction_count  lead_score           0.009888
dtype: float64

### Question 3

- Calculate the mutual information score between `converted` and other categorical variables in the dataset. Use the training set only.
- Round the scores to 2 decimals using `round(score, 2)`.

Which of these variables has the biggest mutual information score?

- `industry`
- `location`
- `lead_source`
- `employment_status`

In [38]:
from sklearn.metrics import mutual_info_score
def mutual_info_churn_score(series):
    return mutual_info_score(series, df.converted)
mi = df[categorical_columns].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)

lead_source          0.026574
employment_status    0.011070
industry             0.007267
location             0.001427
dtype: float64

### Question 4

- Now let's train a logistic regression.
- Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
- Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
  - `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

- 0.64
- 0.74
- 0.84
- 0.94

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   lead_source               1462 non-null   object
 1   industry                  1462 non-null   object
 2   number_of_courses_viewed  1462 non-null   int64
 3   annual_income             1462 non-null   float64
 4   employment_status         1462 non-null   object
 5   location                  1462 non-null   object
 6   interaction_count         1462 non-null   int64
 7   lead_score                1462 non-null   float64
 8   converted                 1462 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 102.9+ KB

In [40]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']
target = 'converted'

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [42]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']

numerical = ['number_of_courses_viewed', 
             'annual_income', 
             'interaction_count', 
             'lead_score']

target = 'converted'

In [43]:

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)


df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [44]:
y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values

In [46]:
train_dict = df_train[categorical + numerical].to_dict(orient='records')
val_dict = df_val[categorical + numerical].to_dict(orient='records')

dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dict)
X_val = dv.transform(val_dict)

In [47]:
model = LogisticRegression(
    solver='liblinear', 
    C=1.0, 
    max_iter=1000, 
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [48]:
y_pred = model.predict(X_val)
acc = accuracy_score(y_val, y_pred)

print("Validation Accuracy:", round(acc, 2))

Validation Accuracy: 0.7

### Question 5

- Let's find the least useful feature using the _feature elimination_ technique.
- Train a model using the same features and parameters as in Q4 (without rounding).
- Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
- For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?

- `'industry'`
- `'employment_status'`
- `'lead_score'`

> **Note**: The difference doesn't have to be positive.

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd


categorical = ['lead_source', 'industry', 'employment_status', 'location']
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']
target = 'converted'


df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

y_train = df_train[target].values
y_val = df_val[target].values


def train_and_evaluate(train_df, val_df, cat_cols, num_cols):
    dv = DictVectorizer(sparse=False)
    train_dict = train_df[cat_cols + num_cols].to_dict(orient='records')
    val_dict = val_df[cat_cols + num_cols].to_dict(orient='records')

    X_train = dv.fit_transform(train_dict)
    X_val = dv.transform(val_dict)

    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    return accuracy_score(y_val, y_pred)

base_acc = train_and_evaluate(df_train, df_val, categorical, numerical)
print("Base accuracy:", base_acc)


results = {}

for feature in categorical + numerical:
    temp_cat = [f for f in categorical if f != feature]
    temp_num = [f for f in numerical if f != feature]

    acc = train_and_evaluate(df_train, df_val, temp_cat, temp_num)
    diff = base_acc - acc
    results[feature] = diff


results_df = pd.DataFrame.from_dict(results, orient='index', columns=['accuracy_diff'])
results_df.sort_values(by='accuracy_diff', ascending=True)

Base accuracy: 0.6996587030716723

                          accuracy_diff
annual_income                 -0.153584
location                      -0.010239
lead_score                    -0.006826
lead_source                   -0.003413
industry                       0.000000
employment_status              0.003413
number_of_courses_viewed       0.143345
interaction_count              0.143345

### Question 6

- Now let's train a regularized logistic regression.
- Let's try the following values of the parameter `C`: `[0.01, 0.1, 1, 10, 100]`.
- Train models using all the features as in Q4.
- Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these `C` leads to the best accuracy on the validation set?

- 0.01
- 0.1
- 1
- 10
- 100

In [51]:
for C in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_val)
    acc = accuracy_score(y_val, y_pred)
    print(f"C={C}: Accuracy={acc:.3f}")

C=0.01: Accuracy=0.700
C=0.1: Accuracy=0.700
C=1: Accuracy=0.700
C=10: Accuracy=0.700
C=100: Accuracy=0.700